name: Bug Report
description: Report a bug to help us improve.
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## IS THIS BUG FOR V5 OR V4?
        > THIS BUG REPORT IS ONLY FOR THE V5. v4 issues should be reported [here](https://github.com/antoniandre/vue-cal-v4/issues).

  - type: input
    id: vue-cal-version
    attributes:
      label: "Vue Cal Version"
      description: "Specify the version of Vue Cal you are using (e.g., 5.0.0)."
      placeholder: "e.g., 5.0.0"
    validations:
      required: true

  - type: input
    id: vue-version
    attributes:
      label: "Vue Version"
      description: "Specify the version of Vue you are using (e.g., 3.3.0)."
      placeholder: "e.g., 3.3.0"
    validations:
      required: true

  - type: checkboxes
    id: additional-settings
    attributes:
      label: "Additional Settings"
      description: "Check all that apply."
      options:
        - label: "Using Composition API"
        - label: "Using SSR"

  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the Bug & Expected Behavior"
      description: "Provide a clear and concise description of the bug and what you expected to happen. Add screenshots if helpful."
      placeholder: "Describe the bug and expected behavior here..."
    validations:
      required: true

  - type: textarea
    id: reproduction-link
    attributes:
      label: "Provide a Reproduction Link"
      description: |
        Provide a link to reproduce the issue by forking one of our examples on StackBlitz:

        - [Vue Cal 5: Basic (Vue 3 + Vite)](https://stackblitz.com/edit/vuecal5?file=src%2FApp.vue)
        - [Vue Cal 5: Events (Vue 3 + Vite)](https://stackblitz.com/edit/vuecal5-events?file=src/App.vue)

        If not possible to reproduce, describe the detailed steps to reproduce the behavior:
          1. Go to '...'
          2. Click on '...'
          3. See error
      placeholder: "Paste reproduction link here"
    validations:
      required: true
